### ISSUE TITLE
existing atom key bindings

### ISSUE THREAD

**Issue by jacekkopecky** [joseramonc/multi-cursor#10]
I just became aware that Atom has its own commands, `editor:add-selection-above` and `...-below` with key bindings different from multi-cursor's. Perhaps this package could use/override the default key bindings from Atom?

**Comment by wolftune** [comment]
I vote for _use_ the existing key bindings rather than override with these extra complex ones.

**Comment by jacekkopecky** [comment]
@wolftune ah, right - I meant use the existing Atom key bindings but override their default action with the functionality from _multi-cursor_ Is that what you mean too?

**Comment by wolftune** [comment]
@jacekkopecky yes, except that in the cases where the actions are the same, obviously there's nothing to override.

**Comment by jacekkopecky** [comment]
Ah but you are mistaken sir, the actions aren't quite the same. :smile:

multi-cursor's adding of selections can also remove selections (try going up and then down - Atom will keep adding, multi-cursor allows you to correct the selections when you've overdone it).

**Comment by wolftune** [comment]
ah nice, but yes, it should just replace the existing keybinding, not use a new additional more complex one.

**Comment by joseramonc** [comment]
Overriding those commands sounds good to me, I wasn't aware of those commands by atom, this would be resolved just by changing the default keybindings to the atom's keybindings?

**Comment by wolftune** [comment]
I think so, yes, it means one less key to deal with. Potentially, the four-modifier options could then be switched to three.

**Comment by joseramonc** [comment]
Fixed by #13
