### ISSUE TITLE
support Linux keybindings, can't use left-right currently

### ISSUE THREAD

**Issue by wolftune** [joseramonc/multi-cursor#11]
cmd is OS X key, not used as much on Linux. Also, the complex combination that allows moving cursor up/down works for me but left/right does not.

**Comment by joseramonc** [comment]
Can you tell what action does the keybind resolver is resolving to with those commands?

I don't have a linux machine at the moment to test with linux keybindings, but if you send a pull request with keybindings for linux specifically I'd be happy to merge it.

**Comment by wolftune** [comment]
Strangely, I now see that alt-shift-cmd-left for skipping up works but the same with the right arrow does not. Also, I was confused about needing to do that and _then_ do the normal up to actually get the new cursor, but I get that now.

Also the alt-cmd-ctrl-shift options work with the left arrow but not the right arrow.

When I try with right-arrow, I don't get any indication in the resolver at all!

**Comment by joseramonc** [comment]
Does this get fixed with the new keybindings in 2.0.0?

**Comment by wolftune** [comment]
Almost everything is working great, except the alt-shift-ctrl-up command is missing for Linux, I only have the other three arrows (left, right, down) working.

**Comment by joseramonc** [comment]
Can you tell me again what's resolving on the keybind resolver? Or if it's and OS shortcut can you send me a keybinding that works on Linux? I'm sorry but I can't test this myself

**Comment by wolftune** [comment]
@joseramonc look at line 38 in https://github.com/joseramonc/multi-cursor/blob/master/keymaps/multi-cursor.cson — it's literally the case that just the up line is missing. It only has the other three directions.

**Comment by joseramonc** [comment]
You're right, sorry, should be fixed in `2.1.0` :+1:
