### ISSUE TITLE
support motion commands for last cursor made

### ISSUE THREAD

**Issue by wolftune** [joseramonc/multi-cursor#12]
I use vim-mode specifically, but any other motion command might work if there were some starting command saying to be moving the last cursor only. I'd like to be able to jump only the last created cursor to a specific place using the same commands as with one cursor.

**Comment by joseramonc** [comment]
Sorry I'm not sure if I get this one right, you'd like some command like `Go to line:toggle` but only for the last cursor?

**Comment by wolftune** [comment]
What I'm saying is that multi-cursor already supports moving just the last cursor. I want to have full control to do arbitrary things to the last cursor, just like I would with a single cursor. Thus Vim commands like fp (find the `p`) or 6w (move 6 words) etc. — basically to just have all normal single-cursor movements available to act on just the last cursor.

Incidentally _most_ movement commands successfully work on the combination of multiple cursors already, I just would like to be able to act on only the last one in order to get multi cursors wherever, kind of like how ctrl-click can put them wherever with the mouse cursor.

Currently, multi-cursor supports this but only via the tedium of moving one character at a time with arrows.

**Comment by joseramonc** [comment]
@wolftune Unfortunately I can't help with this one since I'm not familiarised with vim-mode. However, if you can send a pull request that achieves what you want I'd be more than happy to merge it.

**Comment by wolftune** [comment]
@joseramonc I'll leave it up to you to either leave this open for others or to close it and we can let the vim-mode project figure this out (I think there's some discussion there already). I don't know enough about how to do anything about this myself.
