### ISSUE TITLE
Feature suggestion : multi cursors search

### ISSUE THREAD

**Issue by vjau** [joseramonc/multi-cursor#15]
Hi,
there is a feature that is REALLY useful in Webstorm/Intellij, that's what i would call "multi cursor search" (i don't know if there is an official name).
When you put your cursor under a name, let's say 'foo', and hit alt+j, the word is selected. Hit alt+j again and the next occurence of the word in the file is added to the selection AND a new cursor is created at this occurence. Hit alt+j again and it continues to select words/add cursor.
This is very useful to allow fast and controlled "search and replace" with multiple cursors.
Thank you.

**Comment by joseramonc** [comment]
Atom has a build in feature <kbd>cmd</kbd> + <kbd>D</kbd> that sounds like what you're telling me. Do you want something more specific than this behavior?

**Comment by vjau** [comment]
Didn't know about ctrl + D / command + D, thank you. 
Perhaps it could be added in your doc, for the poor soul like me ;)

**Comment by dpo** [comment]
:+1:
