### ISSUE TITLE
Conflict with core keybinding

### ISSUE THREAD

**Issue by ThaisRobba** [joseramonc/multi-cursor#20]
Atom Core uses ctrl-alt-left/right for moving between subword boundaries.

**Comment by dminca** [comment]
also <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>UP</kbd>/<kbd>DOWN</kbd> is conflicting on *Ubuntu 16.04.1 LTS xenial*

Currently using this workaround:

```coffeescript
'atom-text-editor':
  'alt-shift-k': 'editor:move-line-up'
  'alt-shift-j': 'editor:move-line-down'
  'ctrl-shift-up': 'editor:add-selection-above'
  'ctrl-shift-down': 'editor:add-selection-below'
```

**Comment by joseramonc** [comment]
Can you send a pull request with those as the default for linux? That looks good to me
