### ISSUE TITLE
im new to this and i really need this one im from intellij

### ISSUE THREAD

**Issue by spurdow** [joseramonc/multi-cursor#21]
im new to this and i really need this one im from intellij, how do i install this?

**Comment by spurdow** [comment]
apm install multi-cursor

**Comment by joseramonc** [comment]
This package is for [atom](https://github.com/atom/atom), the easiest way to install it is inside the atom's settings (<kbd>cmd</kbd>+<kbd>,</kbd>) and install it from there.

I don't think this will work in intellij, were you able to install it?

**Comment by spurdow** [comment]
sorry if my question was unclear, actually what i meant is 'im from intellij' is that im new to atom and my experience is from intellij so, Im a beginner in atom installing some packages., But i reread atom installing packages docs, so I already know how. thanks though, It was a stupid question
