### ISSUE TITLE
Is there a way I can bind alt-clicking?

### ISSUE THREAD

**Issue by lucaschen** [joseramonc/multi-cursor#22]
I don't know if you've used Coda before, but Coda has this multi-cursor functionality where you can click on a line with alt held down, and it will include that line in the multi-cursor mode.

Is it possible to bind such a click event to this plugin?

**Comment by joseramonc** [comment]
This plugin don't have an option to map events on click. But atom has a `cmd-click` (`ctrl-click` on linux or windows) that adds a new cursor where you click.

Does this resolve your problem?

**Comment by lucaschen** [comment]
Yep, that completely fixes it. I didn't know that existed - I was looking for alt-click functionality. Thanks for that!
