### ISSUE TITLE
Support: Hold alt and click for new cursor

### ISSUE THREAD

**Issue by caJaeger** [joseramonc/multi-cursor#23]
I don't always want my cursor on the next line up or down, would be nice to be able to hold alt and click where you want your next cursor.

**Comment by joseramonc** [comment]
Related to #22, there's no support for this case right now, but it would be nice to have. If you can help with this feature I'd be happy to merge it.

**Comment by caJaeger** [comment]
@joseramonc The ticket you linked actually perfectly addresses my needs, I didn't realize that was built in already, thanks!

**Comment by joseramonc** [comment]
Glad I could help you!, don't hesitate on opening a new issue if you need more help.
