### ISSUE TITLE
Feature request: additional clicks

### ISSUE THREAD

**Issue by ChrisBAshton** [joseramonc/multi-cursor#24]
I come from a Sublime2 background :) What I miss, and what this package ALMOST gives me fully, is the multi-cursor abilities in Sublime.

Specifically:
- Click somewhere, hold ALT while clicking somewhere else => creates two cursors
- Hold ALT, mouse down where you want your first cursor to be, drag mouse down to create multiple cursors, release ALT and release mouse.

Would it be possible to add these?

**Comment by joseramonc** [comment]
Alt clicking is related to #22, maybe that resolves your issue.

There's a package for mouse selection called [atom-sublime-select](github.com/bigfive/atom-sublime-select) I think you can use that one.

I hope those links resolve your issues.

**Comment by ChrisBAshton** [comment]
Fantastic, that answers both my requests. Thank you!
