### ISSUE TITLE
Support VIM-Bindings

### ISSUE THREAD

**Issue by ldelossa** [joseramonc/multi-cursor#25]
Anyway to get this to work with alt-j and alt-k while in VIM edit mode? Would be a nice to have.

**Comment by joseramonc** [comment]
I'm not sure about how vim edit mode works, the commands can't be mapped to `alt-j` and `alt-k` in vim mode?

If there have to be some additional command [at the keymap](https://github.com/joseramonc/multi-cursor/blob/master/keymaps/multi-cursor.cson) I'd be happy to add them to this repo.
