### ISSUE TITLE
Handling of empty lines

### ISSUE THREAD

**Issue by ggreif** [joseramonc/multi-cursor#28]
When you have a buffer like this:
```
  aaaaaaa

  bbbbbb
```
and you have a cursor before the first `a`, then you create a multi-cursor by option/alt-down over 3 lines. Now hit the `->` key and all of sudden you have 2 cursors in the `bbbbbb` line. Not sure it this is a bug or a feature.

**Comment by joseramonc** [comment]
That happens because the cursor in the second line (empty line) moves to the third line (`bbbbbb` line)

The second line's next `->` position is the third line, it's the same behavior with a single cursor if you press `->` on the empty line.
