### ISSUE TITLE
mouse Selection

### ISSUE THREAD

**Issue by AndyRizzuto** [joseramonc/multi-cursor#3]
I really like the idea but would also want to be able to hold down alt/option and drag with mouse to select multiple lines... guess that selection behavior would be another request.

**Comment by joseramonc** [comment]
@AndyRizzuto It's a nice a feature but there are alredy other packages for that, that's why I didn't tried to do it, have you tried [sublime selection](https://github.com/bigfive/atom-sublime-select)?

**Comment by AndyRizzuto** [comment]
Thanks for the response.  I finally found Sublime-Style-Column-Selection package which is exactly what I was looking for.
