### ISSUE TITLE
FR: alt+mouse click for any position 

### ISSUE THREAD

**Issue by sylvain-bougnoux** [joseramonc/multi-cursor#32]
It would be interesting to have any location, ie not only up & down, eg controlled by mouse-click. 
For instance to cover 1 every 2 lines or any easy to understand situation.

Thanks anyway

**Comment by sylvain-bougnoux** [comment]
Sorry: ctrl+click does the job by default; the multi-cursor-plus add-in allows this as well with keyboard only.

**Comment by FlorianWendelborn** [comment]
<kbd>⌘</kbd>+<kbd>Click</kbd> for the macOS master race.
