### ISSUE TITLE
Switching into multi cursor mode by pressing the Alt Key once

### ISSUE THREAD

**Issue by johannesjh** [joseramonc/multi-cursor#33]
Feature request: I would like to suggest the following feature: 

Given a selection in Atom,
when I press a configurable key (default config: Alt-Key),
the selection should toggle into  multi cursor mode and create one caret per line.

The above feature is already implemented in TextMate. It allows to very conveniently create multiple editing carets. For further reference, see: http://blog.macromates.com/2011/multiple-carets/

**Comment by mshenfield** [comment]
There's actually already a built-in Atom command for this. `Editor: Split Selection Into Lines` (Shift + Cmd + L on OSX).

**Comment by FlorianWendelborn** [comment]
@joseramonc @johannesjh I suppose this can be closed.

**Comment by johannesjh** [comment]
yes, thank you!

note: could you maybe document is in the readme?

**Comment by joseramonc** [comment]
@johannesjh If you can write the help note in the readme I'd appreciate it.
