### ISSUE TITLE
Very slow with a lot of lines

### ISSUE THREAD

**Issue by adamreisnz** [joseramonc/multi-cursor#35]
This package is very useful not only for simple coding on multiple lines, but also when dealing with large JSON objects and for example adding or modifiying properties on all of them (where find & replace doesn't suffice, due to for example line endings).

However, when dealing with large data sets and a lot of cursors (100+) this becomes extremely slow to process a single keystroke.

Is there a way to maybe analyze and optimize this a bit and make it a bit more responsive? Feels like it shouldn't be so sluggish with just 100-300 cursors, but I don't know what's going on behind the scenes.

**Comment by joseramonc** [comment]
I'm closing this, since this is a performance bug in atom rather than this package. You should open a ticket there so they can help you and fix this bug.
