### ISSUE TITLE
Why linux keymaps are different and so stupid?

### ISSUE THREAD

**Issue by ghost** [joseramonc/multi-cursor#37]
They even don't works! In GNOME with ctrl + shift + alt + arrows you moving windows to another desktops!

I changed my hotkeys to macos-preset and now they works fine. I just amazed, why they are so bad by default?

**Comment by joseramonc** [comment]
I was helped in #11 and #20 to get those keybinding working, they look good to me as they work well in ubuntu and I think it's a very popular linux plataform, I don't know if atom supports special keybindings for different linux platoforms, If so, I'd be happy to accept your proposed changes for gnome. 

Also, as [noted in the readme](https://github.com/joseramonc/multi-cursor#custom-keymaps) you can turn off keybindings and use your own if you want something else.
