### ISSUE TITLE
moving last cursor

### ISSUE THREAD

**Issue by jacekkopecky** [joseramonc/multi-cursor#4]
Hi, I was just thinking about creating this package, so I searched and found yours instead. Good work!

I would like to propose adding four new actions for a more visible manipulation of the next place: moving only the last cursor.

I use this in my `init.coffee`:

```
atom.commands.add "atom-text-editor", "mine:last-cursor-up", ->
  atom.workspace.getActiveTextEditor().getLastCursor().moveUp()
  atom.workspace.getActiveTextEditor().mergeCursors()

atom.commands.add "atom-text-editor", "mine:last-cursor-down", ->
  atom.workspace.getActiveTextEditor().getLastCursor().moveDown()
  atom.workspace.getActiveTextEditor().mergeCursors()

atom.commands.add "atom-text-editor", "mine:last-cursor-left", ->
  atom.workspace.getActiveTextEditor().getLastCursor().moveLeft()
  atom.workspace.getActiveTextEditor().mergeCursors()

atom.commands.add "atom-text-editor", "mine:last-cursor-right", ->
  atom.workspace.getActiveTextEditor().getLastCursor().moveRight()
  atom.workspace.getActiveTextEditor().mergeCursors()
```

This way, instead of a blind skipping of lines, I can position the cursor that was last added wherever I want.

I can do a PR if you like this.

**Comment by joseramonc** [comment]
This is very helpful, if you can help with a pull request it would be nice :+1:
