### ISSUE TITLE
For Windows, "alt" doesn't work; instead it's the "Windows" key

### ISSUE THREAD

**Issue by stevenmchoi** [joseramonc/multi-cursor#41]
Hi, I tried using "alt" but it didn't work. It works when I use the "Windows" key. However, the downside is that whenever I press the Windows key, it takes me to the Windows Start menu, and I don't want that. I use Windows 8.1. Could you make an improvement? Thanks!

**Comment by catileptic** [comment]
For me, on Windows 10, what allowed me to create a cursor  was `ctrl+alt+up` and `ctrl+alt+down`.

**Comment by joseramonc** [comment]
Unfortunately I don't have a machine to test in windows, however, if you could send a PR changing the keybinding for one that could be used as the default I'd be more than happy to merge it.
