### ISSUE TITLE
New cursor on next occurance

### ISSUE THREAD

**Issue by lhunath** [joseramonc/multi-cursor#42]
A very popular way of creating a new cursor in other applications with multi-cursor support is to spawn the cursor on the next occurrence of the active selection, with that occurrence selected.  Since multi-cursors are generally used for editing multiple locations in the exact same way, that usually only makes sense when they already contain the same text, and therefore, this method is an extremely efficient way of spawning cursors in the right location without having to tweak them after spawning.

**Comment by joseramonc** [comment]
I think what you're looking for is `find-and-replace:select-next` (on mac: <kbd>cmd</kbd> + <kbd>d</kbd>) or how is this feature different from that?

**Comment by lhunath** [comment]
... yeah.  I was unaware of this.  Apologies!
