### ISSUE TITLE
How to change from multi-cursor to one-cursor?

### ISSUE THREAD

**Issue by sakya0608** [joseramonc/multi-cursor#43]
Many people may prefer to type without mouse and they may have the same issue like me.
I have a solution about that:
alt+left/right to move all the cursors 
left/right to move the last cursor and delete all the previous ones.
It will be really nice if you can update this. Thanks a lot!

**Comment by joseramonc** [comment]
You can change from many cursor to one by pressing <kbd>esc</kbd> key, perhaps do you need a way to press escape and make the last cursor the active?

**Comment by sakya0608** [comment]
Thanks for the reply. The function of esc key is good enough for me !
