### ISSUE TITLE
Working great until recently

### ISSUE THREAD

**Issue by softwarecreations** [joseramonc/multi-cursor#49]
I've been using this plugin for years.
Recently it stopped working.
I try the default key-bindings (that are definitely enabled) but nothing happens at all.
My various other plugins that also use keybindings, that I've also had installed for years are still working fine. I haven't changed any plugin installation status in many months.

Atom 1.40.1 x64 on Linux
multi-cursor 3.0.0

**Comment by joseramonc** [comment]
Hello! I'm sorry for this, I suspect this is a keybinding issue (changed recently)

Could you show me what key bind is resolving please? (You can check this via the key binding resolver). it should show something like this:
<img width="991" alt="image" src="https://user-images.githubusercontent.com/1993929/67581539-ca2b9480-f70d-11e9-93e6-86b1ac0cf6dd.png">

Also, if the multicursor keybinds are overrided by your keymap?

**Comment by softwarecreations** [comment]
Hi @joseramonc no worries my friend. Thanks for your reply :)

EDIT Wow, I'm sorry. I feel really dumb now :)
I just noticed that I had old keybindings above in my keymap.cson that I had forgotten about.

```
 'alt-shift-up':     'multi-cursor:expandUp';
 'alt-shift-down':   'multi-cursor:expandDown';
```
They were the entire cause of the problem. It looks like you've renamed the functions from expandUp to expand-up and expandDown to expand-down. So my binding was triggering but couldn't find the function anymore since you (probably) changed it?

Anyways, the rest was of this message was my debugging, which I'll leave here incase anyone else is interested in my alternative keybinding successes and failures.

---

This is what the keybinding resolver looks like with the default keybindings and no custom keybindings related to multi-cursor
![image](https://user-images.githubusercontent.com/28704571/67942740-2fd1c200-fbe1-11e9-9846-f47c4ebd185b.png)

I've got the default keybindings enabled, as always
![image](https://user-images.githubusercontent.com/28704571/67942852-76272100-fbe1-11e9-8c1b-f3104918f17a.png)

As an experiment I just created a random key-binding to test, and it works:
`'ctrl-alt-i': 'multi-cursor:expand-down'`

So I did more experiments now:
These don't work
`'alt-shift-down': 'multi-cursor:expand-down'`
`'alt-down': 'multi-cursor:expand-down'`
`'ctrl-down': 'multi-cursor:expand-down'`

This works `'alt-shift-2': 'multi-cursor:expand-down'` (using numpad)

Okay I found a workaround: (this works)
`'ctrl-alt-shift-down': 'multi-cursor:expand-down'`
Looks like this
![image](https://user-images.githubusercontent.com/28704571/67943740-67da0480-fbe3-11e9-862a-57bed4d3095b.png)

`'shift-ctrl-down': 'multi-cursor:expand-down'` also works
![image](https://user-images.githubusercontent.com/28704571/67943848-a5d72880-fbe3-11e9-8bef-db3cb63cca73.png)

ctrl-shift-down is arguably nicer (easier to press) than alt-shift-down so I'm perfectly happy with this.
However it's not nice that the keybindings don't seem to work with the default keybindings that the package comes with.

**Comment by softwarecreations** [comment]
Also, check out the multi-cursor-increment package with the following keybindings; they synergize nicely. (multi-cursor default keybindings disabled)
```
  'alt-shift-up': 'multi-cursor:expand-up'
  'alt-shift-down': 'multi-cursor:expand-down'
  'ctrl-shift-up': 'multi-cursor-increment:increment'
  'ctrl-shift-down': 'multi-cursor-increment:decrement'```

**Comment by joseramonc** [comment]
Glad you solved it! Yes those keybidings names were refactored recently to use the same conventions for all multi-cursor commands.

Thanks for all the detailed information!
